import type { DisplayItem } from '@/types';

export const SAMPLE_ITEMS: DisplayItem[] = [
  {
    id: "doj-us-attorney-firings",
    type: "stories",
    alarm: 5,
    category: "Justice & Legal",
    status: "active",
    published: "2026-04-14",
    updated: "2026-04-17",
    headline_spicy: "They fired the prosecutors investigating the president's friends. On a Tuesday.",
    headline_neutral: "DOJ removes 14 U.S. Attorneys mid-case",
    dek: "Fourteen U.S. Attorneys — every one of them overseeing an active case touching a Trump donor, appointee, or family member — were walked out of their offices before lunch.",
    body: "The firings happened in a four-hour window. By the time reporters reached the buildings, the nameplates were gone. Three of the fired attorneys were overseeing grand jury proceedings.",
    sources: [
      { label: "DOJ Memo (4/14)", url: "#" },
      { label: "WaPo reporting", url: "#" },
      { label: "Letter from 112 former federal prosecutors", url: "#" },
    ],
    tags: ["DOJ", "Pam Bondi", "grand jury", "obstruction"],
  },
  {
    id: "eo-military-domestic",
    type: "eos",
    alarm: 5,
    category: "Civil Liberties",
    status: "active",
    published: "2026-03-28",
    updated: "2026-04-11",
    headline_spicy: "EO 14,312 lets the Army run police operations in nine cities. They actually fucking did it.",
    headline_neutral: "Executive Order 14,312 authorizes military support to domestic law enforcement in nine cities",
    dek: "Chicago, Oakland, Minneapolis, Baltimore, New Orleans, Memphis, Detroit, St. Louis, Atlanta. The list is not random.",
    body: "The order invokes the Insurrection Act in peacetime.",
    sources: [
      { label: "Federal Register", url: "#" },
      { label: "Brennan Center analysis", url: "#" },
      { label: "Multi-state complaint", url: "#" },
    ],
    tags: ["military", "Insurrection Act", "Posse Comitatus"],
  },
  {
    id: "scotus-emoluments",
    type: "scotus",
    alarm: 4,
    category: "Corruption & Scandals",
    status: "active",
    published: "2026-04-02",
    updated: "2026-04-02",
    headline_spicy: "SCOTUS 6-3: The president can sell access. They called it 'inherent executive discretion.'",
    headline_neutral: "SCOTUS narrows Emoluments Clause enforcement in Trump v. CREW",
    dek: "The majority opinion holds that private citizens lack standing to sue over foreign payments to the president's businesses.",
    body: "The question presented was narrow. The answer was not.",
    sources: [
      { label: "Opinion (PDF)", url: "#" },
      { label: "Sotomayor dissent", url: "#" },
    ],
    tags: ["SCOTUS", "Emoluments", "Alito"],
  },
  {
    id: "pardon-chesebro",
    type: "pardons",
    alarm: 5,
    category: "Democracy & Elections",
    status: "closed",
    published: "2026-02-20",
    updated: "2026-02-20",
    headline_spicy: "Pardon #47: the fake-electors lawyer. Paid $2.3M to the inaugural committee in January.",
    headline_neutral: "Presidential pardon issued to Kenneth Chesebro",
    dek: "The man who wrote the December 2020 memo laying out the fake-elector strategy received a full pardon four months into his sentence.",
    body: "The pardon covers all federal charges stemming from the January 6 investigation.",
    sources: [
      { label: "White House proclamation", url: "#" },
      { label: "FEC filing", url: "#" },
    ],
    tags: ["pardon", "January 6", "fake electors"],
  },
  {
    id: "epstein-doj-files",
    type: "stories",
    alarm: 4,
    category: "Epstein & Associates",
    status: "active",
    published: "2026-04-09",
    updated: "2026-04-16",
    headline_spicy: "DOJ 'misplaced' three boxes of Epstein flight logs. This is the fourth time.",
    headline_neutral: "Justice Department acknowledges missing Epstein-related records",
    dek: "A spokesperson told the Senate Judiciary Committee that 'certain physical records' cannot be located.",
    body: "The missing records include pilot logs from the Zorro Ranch airstrip.",
    sources: [
      { label: "Senate Judiciary letter", url: "#" },
      { label: "DOJ written response", url: "#" },
    ],
    tags: ["Epstein", "DOJ", "subpoena"],
  },
  {
    id: "fcc-license-threats",
    type: "stories",
    alarm: 4,
    category: "Media & Disinformation",
    status: "active",
    published: "2026-04-05",
    updated: "2026-04-15",
    headline_spicy: "FCC chair to network CEOs: cover us nicely or lose your licenses. On a recorded call.",
    headline_neutral: "FCC Chairman initiates 'news distortion' review of four networks",
    dek: "The review names ABC, NBC, CBS, and MSNBC. Fox is not on the list.",
    body: "On the call the Chairman refers twice to 'license renewal windows coming up.'",
    sources: [
      { label: "Call recording (excerpt)", url: "#" },
      { label: "FCC notice", url: "#" },
    ],
    tags: ["FCC", "press freedom", "First Amendment"],
  },
  {
    id: "tariff-saudi-carveout",
    type: "stories",
    alarm: 3,
    category: "Foreign Policy",
    status: "active",
    published: "2026-04-08",
    updated: "2026-04-16",
    headline_spicy: "Everyone gets 35% tariffs. Except Saudi Arabia. Who bought a $2B stake in Truth Social last week.",
    headline_neutral: "Trade policy exempts Saudi imports from new 35% tariff",
    dek: "The USTR issued a 'national security carveout' for Saudi Arabia.",
    body: "The carveout covers petroleum, petrochemicals, steel, and aluminum.",
    sources: [
      { label: "USTR memo", url: "#" },
      { label: "TMTG 8-K", url: "#" },
    ],
    tags: ["tariffs", "Saudi Arabia", "TMTG"],
  },
  {
    id: "scotus-voting-rights",
    type: "scotus",
    alarm: 3,
    category: "Democracy & Elections",
    status: "active",
    published: "2026-03-30",
    updated: "2026-03-30",
    headline_spicy: "Section 2 of the Voting Rights Act is now effectively unenforceable. 5-4.",
    headline_neutral: "SCOTUS raises evidentiary bar for Section 2 VRA claims",
    dek: "The ruling rewrites the standard so that proving a violation requires evidence that 'will rarely if ever exist.'",
    body: "Section 2 prohibits voting practices that result in discrimination.",
    sources: [
      { label: "Opinion", url: "#" },
      { label: "Kagan dissent", url: "#" },
    ],
    tags: ["VRA", "Section 2", "voting rights"],
  },
  {
    id: "gop-gerrymander-ohio",
    type: "stories",
    alarm: 2,
    category: "Democracy & Elections",
    status: "active",
    published: "2026-04-11",
    updated: "2026-04-14",
    headline_spicy: "Ohio redrew its map. Again. The algorithm now gives Republicans 13 of 15 seats in a 53% state.",
    headline_neutral: "Ohio legislature passes new congressional map",
    dek: "Ohio's new map survives the anti-gerrymandering amendment by threading a loophole.",
    body: "The loophole: the amendment requires a bipartisan vote only if the map is in effect for ten years.",
    sources: [
      { label: "Map (official)", url: "#" },
      { label: "FairDistricts analysis", url: "#" },
    ],
    tags: ["gerrymander", "Ohio"],
  },
  {
    id: "scotus-trans-care",
    type: "scotus",
    alarm: 0,
    category: "Civil Liberties",
    status: "closed",
    published: "2026-03-25",
    updated: "2026-03-25",
    headline_spicy: "SCOTUS, 5-4, declined to let a state criminalize parents. Do not get comfortable.",
    headline_neutral: "SCOTUS declines to hear Texas v. Doe, leaves injunction in place",
    dek: "The Court declined certiorari in a case that would have allowed prosecution of parents for seeking out-of-state medical care.",
    body: "This is a win. It is also, technically, not a ruling.",
    sources: [
      { label: "Cert denial order", url: "#" },
      { label: "ACLU statement", url: "#" },
    ],
    tags: ["SCOTUS", "trans rights", "Texas"],
  },
];
