# A standard Supabase project configuration file

[api]
enabled = true
port = 54321
schemas = ["public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
major_version = 15

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["http://localhost:3000"]
jwt_expiry = 3600
enable_signup = true

[functions.stories-active]
verify_jwt = false

[functions.stories-detail]
verify_jwt = false

[functions.stories-search]
verify_jwt = false

[functions.articles-manual]
verify_jwt = false
