import { defineConfig, type Plugin } from 'vite';
import react from '@vitejs/plugin-react';
import netlifyPlugin from '@netlify/vite-plugin';
import { resolve } from 'path';

// The app's entire stylesheet is ~1.3KB; as a <link> it is one extra
// render-blocking round trip that delays first paint of the boot skeleton
// (ADO-568). Inline it into index.html and drop the link.
function inlineCss(): Plugin {
  return {
    name: 'tt-inline-css',
    apply: 'build',
    enforce: 'post',
    transformIndexHtml(html, ctx) {
      if (!ctx.bundle) return html;
      for (const [name, asset] of Object.entries(ctx.bundle)) {
        if (!name.endsWith('.css') || asset.type !== 'asset') continue;
        const link = new RegExp(`<link[^>]+href="[^"]*${asset.fileName.split('/').pop()}"[^>]*>`);
        if (!link.test(html)) continue;
        html = html.replace(link, `<style>${asset.source}</style>`);
        delete ctx.bundle[name];
      }
      return html;
    },
  };
}

// Phones re-downloaded the main JS on every visit: Netlify serves everything
// max-age=0, must-revalidate by default (ADO-605). Files in assets/ carry a
// content hash, so they can be cached for a year. Each file this build emitted
// is listed by exact path rather than a /assets/* wildcard: a missing chunk
// (an old tab after a deploy) falls through to the SPA rewrite and gets
// index.html, and a wildcard would pin that HTML in the cache for a year.
// index.html and the flag files keep Netlify's default.
function immutableAssetHeaders(): Plugin {
  return {
    name: 'tt-immutable-asset-headers',
    apply: 'build',
    enforce: 'post',
    generateBundle(_options, bundle) {
      const files = Object.keys(bundle).filter(f => f.startsWith('assets/')).sort();
      const lines = ['# Generated by vite.config.ts (tt-immutable-asset-headers, ADO-605). Do not edit.'];
      for (const f of files) lines.push(`/${f}`, '  Cache-Control: public, max-age=31536000, immutable');
      this.emitFile({ type: 'asset', fileName: '_headers', source: lines.join('\n') + '\n' });
    },
  };
}

export default defineConfig({
  plugins: [react(), netlifyPlugin(), inlineCss(), immutableAssetHeaders()],
  publicDir: 'public',
  build: {
    outDir: 'dist',
    sourcemap: true,
  },
  resolve: {
    alias: {
      '@': resolve(__dirname, 'src'),
    },
  },
  server: {
    port: 3000,
    open: true,
  },
  test: {
    include: ['src/**/*.test.{ts,tsx}'],
  },
});
