# Process Manual Article Submission
# Uses Playwright as fallback for sites that block normal requests
name: Process Manual Article

on:
  workflow_dispatch:
    inputs:
      article_url:
        description: 'Article URL to process'
        required: true
        type: string
      title:
        description: 'Article title (optional)'
        required: false
        type: string
      category:
        description: 'Category'
        required: false
        default: 'Political News'
        type: string
      submitted_by:
        description: 'Submitted by'
        required: false
        default: 'admin'
        type: string
  repository_dispatch:
    types: [process-manual-article]

jobs:
  process-article:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Detect environment
      id: env_detect
      run: |
        echo "Current ref: ${{ github.ref }}"
        echo "Current branch: ${GITHUB_REF#refs/heads/}"
        
        # Check if we're on test branch or if test file exists
        if [[ "${{ github.ref }}" == "refs/heads/test" ]] || [[ -f "TEST_BRANCH_MARKER.md" ]]; then
          echo "environment=test" >> $GITHUB_OUTPUT
          echo "🧪 Using TEST environment"
        else
          echo "environment=production" >> $GITHUB_OUTPUT
          echo "🚀 Using PRODUCTION environment"
        fi
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: |
        npm install
        # Install Playwright browsers for fallback scraping
        npx playwright install chromium
        
    - name: Process article
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        SUPABASE_URL: ${{ steps.env_detect.outputs.environment == 'test' && secrets.SUPABASE_TEST_URL || secrets.SUPABASE_URL }}
        SUPABASE_ANON_KEY: ${{ steps.env_detect.outputs.environment == 'test' && secrets.SUPABASE_TEST_ANON_KEY || secrets.SUPABASE_ANON_KEY }}
        INPUT_DATA: |
          {
            "url": "${{ github.event.inputs.article_url || github.event.client_payload.article_url }}",
            "title": "${{ github.event.inputs.title || github.event.client_payload.title }}",
            "category": "${{ github.event.inputs.category || github.event.client_payload.category || 'Political News' }}",
            "submitted_by": "${{ github.event.inputs.submitted_by || github.event.client_payload.submitted_by || 'admin' }}"
          }
      run: |
        echo "🚀 Processing article..."
        node manual-article-processor.js
        
    - name: Summary
      run: |
        echo "✅ Article processed successfully"
        echo "📎 URL: ${{ github.event.inputs.article_url || github.event.client_payload.article_url }}"
        echo "🎭 Playwright fallback available for complex sites"
