name: RSS Pipeline Health Check

on:
  push:
    paths:
      - 'scripts/job-queue-worker-atomic.js'
      - 'scripts/seed-fetch-jobs.js'
      - 'scripts/rss/**'
      - 'migrations/**'
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours
  workflow_dispatch:

jobs:
  preflight:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run preflight check
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_TEST_URL || secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_TEST_SERVICE_KEY || secrets.SUPABASE_SERVICE_ROLE_KEY }}
        run: |
          echo "🚀 Running preflight check..."
          node scripts/preflight-check.js

      - name: Check job queue state
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_TEST_URL || secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_TEST_SERVICE_KEY || secrets.SUPABASE_SERVICE_ROLE_KEY }}
        run: |
          echo "📊 Checking job queue state..."
          node scripts/diagnose-job-queue.js
