# .github/workflows/test-tracker.yml
name: Test Daily Political Tracker (Manual Only)
on:
  # Only allow manual triggering - no automatic schedule
  workflow_dispatch:
    inputs:
      debug_mode:
        description: 'Enable debug output'
        required: false
        default: 'true'
        type: boolean

jobs:
  test-tracker:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm install
      
    - name: Run test tracker
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: node test-tracker.js
      
    - name: Test file copy and sizes
      run: |
        echo "=== BEFORE COPY ==="
        echo "Master file size:"
        wc -l master-tracker-log.json || echo "Master file not found!"
        echo "Public file size:"
        wc -l public/master-tracker-log.json || echo "Public file not found!"
        
        echo "=== FILE CONTENTS CHECK ==="
        echo "Last 5 lines of master file:"
        tail -5 master-tracker-log.json || echo "Cannot read master file"
        echo "Last 5 lines of public file:"
        tail -5 public/master-tracker-log.json || echo "Cannot read public file"
        
        echo "=== COPYING ==="
        mkdir -p public
        cp master-tracker-log.json public/master-tracker-log.json
        
        echo "=== AFTER COPY ==="
        echo "Master file size:"
        wc -l master-tracker-log.json
        echo "Public file size:"
        wc -l public/master-tracker-log.json
        
        echo "=== CONTENT VERIFICATION ==="
        echo "Last 5 lines of public file after copy:"
        tail -5 public/master-tracker-log.json
        
        echo "=== DIFF CHECK ==="
        diff master-tracker-log.json public/master-tracker-log.json && echo "Files are identical!" || echo "Files differ!"
     
    - name: Copy data to public folder (backup method)
      run: |
        echo "=== BACKUP COPY METHOD ==="
        ls -la master-tracker-log.json
        mkdir -p public
        ls -la public/
        cp master-tracker-log.json public/master-tracker-log.json
        ls -la public/master-tracker-log.json
        echo "Copy completed successfully"
      
    - name: Commit and push test results
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action - Test Run"
        git add *.json public/*.json
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Test tracker update - $(date +%Y-%m-%d)"
          git push
        fi
        
    # Remove the release creation step for testing
    - name: Test completion summary
      run: |
        echo "=== TEST COMPLETED ==="
        echo "Test run completed at: $(date)"
        echo "Files updated:"
        echo "- master-tracker-log.json"
        echo "- public/master-tracker-log.json"
        echo "Check the repository for updated files."
